### ISSUE TITLE
Is you new approach already available?

### ISSUE THREAD

**Issue by axelmohnen** [abap2UI5/ext-fiori_launchpad_on_premise#1]
Hi oblomov,
Is you new approach already available?
I can't see any source code in the repository.

Does the new approach support the switch of themes?
Maybe with the following parameter we could forward the theme selected by the enduser to ABAP2UI5 (lt_config):
sap-ui-theme=[UI5 theme]

Thanks,
Kind regards
Axel

**Comment by oblomov-dev** [comment]
yes it is available, i developed it on abap steampunk with OData based on CDS.

Switch the branches to find the artifacts you need (also updated the documentation).

There is still some work to do if you want to use this approach on a lower release with segw. You need to create an odata service by yourself and copy the implementation from the cds branch.

Yes the idea of this approach is that it behaves like a normal UI5 app, that means you can switch the theme in the launchpad and the UI5 app also runs in the configured theme. My tests with BTP and BTP launchpad worked fine.

Feel free to give it a try and create an issue if you run into problems.

**Comment by oblomov-dev** [comment]
i updated the repository and documentation. you can give it a try again. if you run into problems just open a new issue. i will close this one.
