### ISSUE TITLE
Error Pull Branch odata_cds

### ISSUE THREAD

**Issue by Th0masMa** [abap2UI5/ext-fiori_launchpad_on_premise#2]
Hi @oblomov-dev,

i receive a error after Pull.

![image](https://github.com/abap2UI5/ext-service_integration/assets/64013300/61a42fed-d3a3-4048-b31f-d78bad7fa695)

On-Prem 2021 SP2

Best Regards
Thomas

**Comment by oblomov-dev** [comment]
ah that's a pity. i generated everything on btp abap environment and hoped it will also work on-premise.

You can try the following:
(1) copy and paste the cds view+abap class manually
(2) generate & activate the service for the cds view in transaction /iwfnd/maint_service
(if possible generate everything in a single package and send it via abapGit as a PR)

Besides that the rest of this approach should work as expected.

best regards.

**Comment by Th0masMa** [comment]
I generate and activate the service.

![image](https://github.com/abap2UI5/ext-service_integration/assets/64013300/c6201ba2-0bcf-4141-9270-f766f7930076)

How do I then configure the Fiori Launchpad on Prem?

Best Regards 
Thomas

**Comment by oblomov-dev** [comment]
nice next you have to deploy the ui5 to your backend system. use the branch ui5_app for this and choose your new odata endpoint as the backend model.

**Comment by oblomov-dev** [comment]
@Th0masMa 
Updated the project again for a better structure and understanding.

This repository focuses now on SAP Fiori Launchpad Integration On-Premise only and it is installable with abapGit.

The main branch contains the segw odata service and an ui5 app and should work out-of-the-box.

**Comment by Th0masMa** [comment]
Hi @oblomov-dev ,

both objects can not imported.
![image](https://github.com/abap2UI5/ext-fiori_launchpad_on_premise/assets/64013300/daa3c148-2160-4917-866d-fa96b10b431a)

**Comment by oblomov-dev** [comment]
I think it is fine, had the same issues sometimes. Go to sicf and check if there are three nodes when you search for zui5 

Then start the ui5 app and see if it works.

**Comment by oblomov-dev** [comment]
Updated the documentation, maybe this also helps:
https://github.com/abap2UI5/abap2UI5-documentation/blob/main/docs/ext-fiori_launchpad_integration/installation.md

**Comment by Th0masMa** [comment]
i have more Entries in SICF. What do I do with these?

![image](https://github.com/abap2UI5/ext-fiori_launchpad_on_premise/assets/64013300/f846ffbb-4150-4799-b39f-cdba3c0a4284)


After Adding Systemalias 

![image](https://github.com/abap2UI5/ext-fiori_launchpad_on_premise/assets/64013300/618db910-c7f4-4c75-814f-3ecb2461a88e)
![image](https://github.com/abap2UI5/ext-fiori_launchpad_on_premise/assets/64013300/aa710fde-eacf-4959-bab9-00244e36a5f3)

Test Service again 
```
<error xmlns="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata">
<code>005056A509B11EE1B9A8FEC11C21D78E</code>
<message xml:lang="de">Ressource für Segment 'z2ui5_odata_srv' nicht gefunden</message>
<innererror xmlns="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata">
<transactionid>A32A800593A800C0E0064ABF4D02E57A</transactionid>
<timestamp>20230806083419.3541050</timestamp>
<Error_Resolution>
<SAP_Transaction>For backend administrators: use ADT feed reader "SAP Gateway Error Log" or run transaction /IWFND/ERROR_LOG on SAP Gateway hub system and search for entries with the timestamp above for more details</SAP_Transaction>
<SAP_Note>See SAP Note 1797736 for error analysis (https://service.sap.com/sap/support/notes/1797736)</SAP_Note>
</Error_Resolution>
</innererror>
</error>
```

TR /IWFND/ERROR_LOG
![image](https://github.com/abap2UI5/ext-fiori_launchpad_on_premise/assets/64013300/5eff1c83-40be-45ef-aba5-fdd6b2f267f8)

If i test it in TR /iwfnd/maint_service
![image](https://github.com/abap2UI5/ext-fiori_launchpad_on_premise/assets/64013300/caf6891d-e07b-4d75-8c91-eaae05914778)

**Comment by oblomov-dev** [comment]
If there are more services, maybe they are accidentally still there because of former installations? Everything with abap2ui5 besides the three nodes i showed in the documentation, you can delete.

OK so in /iwfnd/maint_service the respoonse looks correct, only when you start it in the browser it is not. So it seems more a problem with your gateway configuration. 

Do you use any other OData services in this systems? Can you check if you have the same problem there and if not try to use the similar alias configuration you use in the working odata service.

**Comment by Th0masMa** [comment]
I found the error. The service was on the wrong position.
![image](https://github.com/abap2UI5/ext-fiori_launchpad_on_premise/assets/64013300/92f98310-d418-4123-aabd-d7d4dc42edd9)
